# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

#r_build_args: --no-build-vignettes --no-manual --no-resave-data
#r_check_args: --no-build-vignettes --no-manual

# Test master and dev branches
branches:
    only:
        - master
        - dev

# Test on release, old, and development versions of R
r:
 - oldrel
 - release
 - devel

# BiocInstaller required for 'graph' package from Bioconductor
bioc_required: true

# Set CXX1X for R-devel, as R-devel does not detect CXX1X support for gcc 4.6.3
before_install:
- if [[ "$TRAVIS_R_VERSION_STRING" = 'devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi
