# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"

# Test master and dev branches
branches:
    only:
        - master
        - dev

# Test on release, old, and development versions of R
r:
 - oldrel
 - release
 - devel

# BiocInstaller required for 'graph' package from Bioconductor
bioc_required: true

# Install up-to-date dependencies from GitHub
r_github_packages:
    - itsrainingdata/sparsebnUtils
    - itsrainingdata/ccdrAlgorithm
    - gujyjean/discretecdAlgorithm

